schema_version = "1.0.0"
id = "show_node_editor_center_lines"
version = "1.3.0"
name = "node_editor_center_lines(节点界面中心线)"
tagline = "show_node_editor_center_lines(节点界面中心线)"
maintainer = "W_Cloud(一尘不染)"
type = "add-on"
tags = ["Node", "Geometry Nodes"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://space.bilibili.com/1109241880"
