schema_version = "1.0.0"
id = "gn_total_execution_time"
version = "1.3.0"
name = "show_gn_total_execution_time_in_header_and_editor(几何节点耗时显示在标题栏和界面)"
tagline = "Qucik add/split/merge Group Input node/socket(快速添加拆分合并移动组输入节点接口)"
maintainer = "W_Cloud(一尘不染)"
type = "add-on"
tags = ["Node", "Geometry Nodes"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://space.bilibili.com/1109241880"
