schema_version = "1.0.0"
id = "named_attribute_list"
version = "2.2.1"
name = "Named Attribute List(命名属性列表)"
tagline = "Quickly Add Attribute Node in GN and Shader(几何节点和材质里快速添加属性节点)"
maintainer = "W_Cloud(一尘不染)"
type = "add-on"
tags = ["Node", "Geometry Nodes"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://space.bilibili.com/1109241880"
